/**:
  ros__parameters:
    use_mock: true
    port: "/dev/ttyUSB0"
    baudrate: 19200
    timeout: 0.1
    frame_id: "ft300_sensor_link"
    publish_rate: 100.0
    comm_mode: "datastream"
    slave_id: 9
    validate_crc: true
