controller_manager:
  ros__parameters:
    update_rate: 125
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gantry_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint:
        trajectory: 2.0
        goal: 1.0
      shoulder_lift_joint:
        trajectory: 2.0
        goal: 1.0
      elbow_joint:
        trajectory: 2.0
        goal: 1.0
      wrist_1_joint:
        trajectory: 2.0
        goal: 1.0
      wrist_2_joint:
        trajectory: 7.0
        goal: 7.0
      wrist_3_joint:
        trajectory: 7.0
        goal: 7.0

gantry_trajectory_controller:
  ros__parameters:
    joints:
      - gantry_x_joint
      - gantry_y_joint
      - gantry_z_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.02
      gantry_x_joint:
        trajectory: 1.0
        goal: 0.02
      gantry_y_joint:
        trajectory: 1.0
        goal: 0.02
      gantry_z_joint:
        trajectory: 1.0
        goal: 0.02
