# Inertial parameters of the Franka Hand payload

# Payload mass [kg]
mass: 0.73

# Payload center of mass coordinates (x,y,z) [m]
center_of_mass: [0.0, 0.01, 0.03]

# Payload inertia tensor (Ixx, Ixy, Ixz, Iyy, Iyz, Izz) [kg m^2]
inertia_tensor: [0.001, 0.0, 0.0, 0.0025, 0.0, 0.0017]
